mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('posts/', include('posts.urls'))
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

posts/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.store, name="posts.store"),
    path('results/<title>', views.showResults, name="results"),
    path('search', views.search, name="search")
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.choice_text

posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=60)
    body = models.TextField(max_length=190)
    author = models.CharField(max_length=60, default='Albert')
    edition = models.IntegerField(default=1)
    year = models.IntegerField(default=2019)
    type = models.CharField(max_length=60, default='Libro')
    available = models.BooleanField(default=True)


    def __str__(self):
        return self.title

posts/forms.py
from django import forms
from .models import Post

class PostsForm(forms.Form):

    title = forms.CharField(max_length=5, required=True)
    body = forms.CharField(widget=forms.Textarea)

    class Meta:
        model: 'Post'

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice

# Create your views here.

''' def index(request):
    lasted_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {
        'lasted_question_list': lasted_question_list,
        'title': 'Lista de preguntas'
    }

    return render(request, 'polls/index.html', context) '''
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'lasted_question_list'

    def get_queryset(self):
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

''' def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question}) '''
class DetailView(generic.DeleteView):
    model = Question
    template_name = 'polls/detail.html'

''' def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question}) '''
class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': 'No has seleccionado ninguna opcion'
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id, )))

posts/views.py
from django.shortcuts import render, redirect
from .forms import PostsForm
from .models import Post

# Create your views here.
def store(request):

    if request.method == 'POST':
        form = PostsForm(request.POST)
        if form.is_valid():
            ''' post = Post(title=form.cleaned_data['title'], body=form.cleaned_data['body']) '''
            post = Post()
            post.title = form.cleaned_data['title']
            post.body = form.cleaned_data['body']
            post.save()

            return redirect('posts:posts.store')

    form = PostsForm()
    posts = Post.objects.all()
    return render(request, 'posts/form.html', {'form': form, 'posts': posts})

def showResults(request, title):

    result = Post.objects.get(title=title)

    return render(request, 'posts/result.html', {'result': result})

def search(request):

    if request.method == 'POST':
        title = request.POST['title']
        result = Post.objects.get(title=title)

    else:
        result = 'this is'

    return render(request, 'posts/search.html', {'result': result})

polls/templates/polls/detail.html
<p>
    <h2> {{ question.question_text }} </h2>
    <hr>
    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
        <input type="submit" value="Vote">
    </form>
</p>

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}">

{% if lasted_question_list %}
    <ul>
        {% for question in lasted_question_list %}
            <li>
                <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
            </li>
        {% endfor %}
    </ul>
{% endif %}

polls/templates/polls/results.html
<p>
    <h2> {{ question.question_text }} </h2>
    <hr>
    {% for choice in question.choice_set.all %}
        <h3>{{ choice.choice_text }} votes: {{ choice.votes }}</h3>
    {% endfor %}

    <a href="{% url 'polls:detail' question.id%}">Volver a votar</a>
</p>

posts/templates/posts/form.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'posts:search' %}">Buscar</a>
    <h4>Esto es para confirmar los merge request</h4>
    <form method="post">
        {% csrf_token %}
        {% if form.errors %}
            <p>{{ form.errors }}</p>
        {% endif %}
        {{ form }}
        <button type="submit">Save</button>
    </form>
    <div class="container">
        <h3>Posts</h3>
        <ul>
            {% for post in posts %}
                <li>{{ post.title }}</li>
                <li>{{ post.body }}</li>
                <hr>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

posts/templates/posts/result.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% if result %}
        {{ result.title }}
        {{ result.body }}
    {% else %}
        <p>No hay recursos con esas especifiacioens</p>
    {% endif %}
</body>
</html>

posts/templates/posts/search.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Search</title>
</head>
<body>
    <form method="post" action="{% url 'posts:search' %}">
        {% csrf_token %}
        <input type="text" name="title" placeholder="buscar por titulo">
        <button type="submit">Buscar</button>
    </form>
    <div class="container">
        {% if result %}
            <ul>
                <li>Titulo: {{ result.title }}</li>
                <li>Extracto: {{ result.body }}</li>
                <li>Autor: {{ result.author }}</li>
                <li>Año: {{ result.year }}</li>
                {% if result.available %}
                    <li style="color:green"> Disponible </li>
                {% else %}
                    <li style="color:red"> No disponibke </li>
                {% endif %}
            </ul>
        {% endif %}
    </div>
</body>
</html>